name: Case Management Workflows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v1
      - name: Install SFDX CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install
      - name: "Populate SALESFORCE_AUTH_URL Secret"
        shell: bash
        run: "echo ${{secrets.SALESFORCE_AUTH_URL}} > ./SALESFORCE_AUTH_URL.txt"
      - name: "Authenticate Devhub"
        run: "sfdx force:auth:sfdxurl:store -f ./SALESFORCE_AUTH_URL.txt -a devhub -d"      
      - name: "Create Scratch Org"
        run: "sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1"
      - name: "Deploy to Scratch Org"
        run: "sfdx force:source:push"
      - name: "Run Apex Test"
        run: "sfdx force:apex:test:run -c -r human -d ./tests/apex -w 20"
      - name: "upload Apex Code Coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          flags: Apex
      - name: "Delete Scratch Org"
        if: always()
        run: sfdx force:org:delete -p -u scratch-org

      


     
     